version: "3.9"

services:
  military-db:
    container_name: military-db
    image: "postgres:15.3-bullseye"
    restart: unless-stopped   # if crashes, restart it, if I manually stop it don't do anything
    environment:
      - POSTGRES_USER=postgres  # startup username and password
      - POSTGRES_PASSWORD=postgres
    logging:   # logging size under control
      options:
        max-size: 10m   # m - mb
        max-file: "3"
    ports:
      # external:internal
      - "5445:5432"  # port mapping
    volumes:
      - military-db-postgres-volume:/var/lib/postgresql/data   # maps it to location /var...

# no configuration, make virtual persistent hard disk
# when db image is updated, volume stays in place, files will be kept
volumes:
  military-db-postgres-volume:
